### ISSUE TITLE
Emoteslots

### ISSUE THREAD

**Issue by Hafra93** [Decicus/DecAPI#26]
`        'emoteslots' => [
            0 => 2,
            25 => 4,
            50 => 6,
            100 => 8,
            250 => 10,
            500 => 15,
            1000 => 20,
            2000 => 25,
            3000 => 30,
            4000 => 35,
            5000 => 40,
            6000 => 45,
            7000 => 50
        ],`

This is not correct. Twitch changed the amount of subpoints needed for each emote slot. You can see the new subpoints -> emoteslots table here: [https://help.twitch.tv/customer/portal/articles/2348985](https://help.twitch.tv/customer/portal/articles/2348985) I hope this helps. Also it's not the subscriptions that lead to emoteslots, but it's the subpoints.

**Comment by Decicus** [comment]
Yeah, it's an endpoint that was created before subscriber points and subscriber tiers were even a thing on Twitch, and it was never updated to account for the change from subscriber **count** to subscriber **points**.

I haven't changed it yet, because I'm not exactly sure how I should "fix it" or if it's better to just straight up remove it, since any implementation would be broken a long time ago regardless.

Thanks for reporting it though!
