### ISSUE TITLE
Sub suggestion

### ISSUE THREAD

**Issue by luki1412** [Decicus/DecAPI#36]
Could you add an endpoint for how long the streamer has been partnered? You can base it on the streamers sub length.

Also, is it possible to actually add subbage where you can see the whole length of being subbed to the streamer, regardless of whether it was gifted?

**Comment by Decicus** [comment]
> Could you add an endpoint for how long the streamer has been partnered? You can base it on the streamers sub length.

That's true for newer partners, say the last 2-3 years. Anyone that was partnered a few years ago didn't initially get a lifetime subscription to their own channel and they had to contact Twitch in later years to fix that.

Because of this, I'm not sure I wanna add that kind of endpoint. We already have `/twitch/subage` (even though it's currently 100% broken, due to the Twitch API being broken), which isn't accurate by itself with a good chunk of subs and I'd rather not have to deal with another inaccurate endpoint.

> Also, is it possible to actually add subbage where you can see the whole length of being subbed to the streamer, regardless of whether it was gifted?

Not really. There isn't any API endpoint that covers this properly. The only place where this data is exposed is in chat, and even then it requires the viewers to share their own subscription for this data to be sent.
