### ISSUE TITLE
Allow Steam Hours Endpoint to be multilingual

### ISSUE THREAD

**Issue by Saturate** [Decicus/DecAPI#65]
https://github.com/Decicus/DecAPI/blob/be04af42f32efd23f862bf1c2e57569d2df80059/app/Http/Controllers/SteamController.php#L221

This formatting makes it so that hours are always the unit. I want this to be "timer" to support a danish nightbot. Seeing it's not backward compatible to just remove it, I suggest a parameter that simply disables it, or changes the text. If it's disabled it would be implemented like this 

`!editcom !timer Wonderbai har spillet CSGO i $(urlfetch https://beta.decapi.me/steam/hours?id=76561198058746905&appid=730) timer`

if it's a parameter it would be:

`!editcom !timer Wonderbai har spillet CSGO i $(urlfetch https://beta.decapi.me/steam/hours?id=76561198058746905&appid=730&unittext=timer)`

**Comment by Decicus** [comment]
> This formatting makes it so that hours are always the unit. I want this to be "timer" to support a danish nightbot. Seeing it's not backward compatible to just remove it, I suggest a parameter that simply disables it, or changes the text. If it's disabled it would be implemented like this

`%s hours` in the line you referred to is just the default. You can customize it yourself, where `%s` is just the _number of hours_ and `hours` is just what's added at the end by default:
- Here's an example with just the number `123.45`: https://decapi.me/steam/hours?id=76561198058746905&appid=730&format=%s
- Here's an example with the format `123.45 timer`: https://decapi.me/steam/hours?id=76561198058746905&appid=730&format=%s%20timer

I do agree that the `/steam/hours` endpoint should have translations for _everything else_, but since that's _mostly_ error messages it's a low priority issue.
